FROM python:3.13.7-slim

WORKDIR /usr/src/app/

EXPOSE 8000
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt
COPY ./ /usr/src/app/

ENV PYTHONUNBUFFERED=1

CMD ["fastapi", "run", "api.py"]